# -*- coding: utf-8 -*-
"""Aula1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TPjLzuK6pKtgB10W7V0v7QS737TEgV7s
"""

# Cria variável qtde_alfaces do tipo inteiro e atribui o valor 3 a ela
qtde_alfaces = 3
# Imprime valor da variável qtde_alfaces
print(qtde_alfaces)
# Altera o valor da variável qtde_alfaces para 2
qtde_alfaces = 2
# Imprime o novo valor da variável
print(qtde_alfaces)

# Cria variável tanto_de_peixe do tipo float (ou double) e atribui 1.5 a ela
# Real: 0.0000000000000000119287361278936123896123123512312
# Tipo float e tipo double (floating point number)
tanto_de_peixe = 1.5
# Imprime o tanto de peixe comprado
print(tanto_de_peixe)
# Altera o valor da variável tanto_de_peixe
tanto_de_peixe = 2.5
print(tanto_de_peixe)

# vai_chover = false --> NameError: name 'false' is not defined
# Python é sensível ao caso (case sensitive)
# false = 150
# Cria variável vai_chover do tipo boolean e atribui False a ela
vai_chover = False
print(vai_chover)

nome_cliente = "Zé das Couves"
print(nome_cliente)
nome_cliente = "José das Couves"
print(nome_cliente)
senha_cliente = 'xY-9*=oikl- tw8&'
print(senha_cliente)

# Snake Case
qtde_sacolas = 9
# Camel Case
qtdeSacolas = 9