# -*- coding: utf-8 -*-
"""Aula1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HGLEhUonxU64_T6QQq5Qe9YolxLEqDkY
"""

5 + 3

7 * 20 + (3 / 2)

'Viva' + ' Python!'

'Viva ' * 5

'São 19 horas e 40 minutos. Isso é uma string'

10 * 2

'10 ' * 2