# -*- coding: utf-8 -*-
"""Aula1Exercicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WXzRel7wOig692ZaFraNH_-pIitAZkkz

Fazer um programa que represente a ficha de um cliente. Um cliente possui nome, telefone, endereço, idade (em anos), saldo atual, ativo. Ao final imprimir todos os dados do cliente.
"""

nome_cliente = "José das Couves"
fone_cliente = "(41)8888-8888"
endereco_cliente = "Avenida dos Vegetais, 45"
idade_cliente = 40
saldo_atual = -1500.41
status_ativo = True

print("Ficha do Cliente")
print("Nome: ", nome_cliente)
print("Fone: ", fone_cliente)
print("Endereço: ", endereco_cliente)
print("Idade: ", idade_cliente)
print("Saldo Atual: ", saldo_atual)
print("Está ativo? ", status_ativo)